name: Update Punks Issuances

on:
  schedule:
    - cron: "*/10 * * * *" # This will run the workflow every 10 minutes

jobs:
  update-issuances:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update endBlock in fetchAllIssuances.js
        run: |
          LATEST_BLOCK=$(node -e "const getLatestBitcoinBlock = require('./find/getLatestBitcoinBlock.js'); getLatestBitcoinBlock().then(block => console.log(block));")
          sed -i "s/const endBlock = .*/const endBlock = $LATEST_BLOCK;/" ./find/fetchAllIssuances.js

      - name: Fetch all issuances
        run: node ./find/fetchAllIssuances.js

      - name: Match punks issuances
        run: node ./find/matchPunksIssuances.js

      - name: Update Last Update Block in index.html
        run: |
          LAST_UPDATE_BLOCK=$(grep -oP "Last Update Block: \K\d+" ./find/punksIssuances.json)
          sed -i "s/Last Update Block: [0-9]*/Last Update Block: $LAST_UPDATE_BLOCK/" index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git add ./find/punksIssuances.json ./find/fetchAllIssuances.js index.html
          git commit -m "Update punksIssuances.json and index.html"
          git push
